blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [
    path('', views.index, name='home'),
    path('post/<int:pk>/', views.post, name='post'),
]

home/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='home'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from blog.data import posts
# Create your views here.

def index(request: HttpRequest) -> HttpResponse:
    context = {
        "name": "BLOG",
        "title": "Blog",
        "tema": 'Tema-blog',
        "data": posts
        }
    return render(request, 'blog/home.html',context=context)


def post(request: HttpRequest, pk: int) -> HttpResponse: 
    found_post: dict[str, Any] | None = None
    for item in posts:
        if item['id'] == pk:
            found_post = item
            break

    context = {
        "name": "BLOG",
        "title": f"Post->{item['id']}",
        "tema": 'Tema-post',
        "data": found_post
        }
    
    print(request, pk)
    return render(request, 'blog/post.html', context=context)

home/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.
def index(request):
    context = {
        "name": "HOME",
        "title": "Home",
        "tema": "Tema-home",
        "lista": [c for c in range(10)]
        }
    return render(request, 'home/home.html', context=context)

blog/templates/blog/home.html
{% extends "global/index.html" %}

{% block texto%}
    {{name}}
{% endblock texto%}
{% block info %}{% endblock info %}
{% block posts %}
    {% for item in data %}
    <section class="container">
        <h2><a href="{% url "blog:post" item.id %}" class="post">{{item.title}}</a></h2>
        <p>{{item.body}}</p>
    </section>
    {% endfor %}
{% endblock posts %}

blog/templates/blog/post.html
{% extends "global/index.html" %}

{% block texto %}{{name}}{% endblock texto %}
{% block posts %}
    {% if data %}
        <h2>{{data.title}}</h2>
        <p>{{data.body}}</p>
    {% else %}
        <h2>Post não encontrado</h2>
    {% endif %}
{% endblock posts %}
{% block info %}{% endblock info %}

home/templates/home/home.html
{% extends "global/index.html" %}

{% block texto %}
    {{name}}
{% endblock texto %}
{% block info %}
{% for item in lista %}
<section class="container">
    <h2>{{tema}}_{{item}}</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, culpa, blanditiis molestiae quas temporibus nemo commodi sapiente ullam odit vitae fugit. Quo, corporis placeat necessitatibus molestiae ea ex ut fugit?Lorem ipsum dolor sit amet consectetur adipisicing elit. Deleniti at blanditiis quam natus maiores aperiam fuga officiis, nobis beatae totam? Quasi, iure. Corporis, magnam doloribus eius voluptas ratione qui minima?</p>
</section>
{% endfor %}
{% endblock info %}
{% block posts %}{% endblock posts %}

templates/global/index.html
<!DOCTYPE html>
<html lang="pt-br">
    {% include "./partials/head.html" %}
<body>
    {% include "./partials/menu.html" %}
    <h1>
        {% block texto %}<!--Adicione um texto aqui-->{% endblock texto %}
    </h1>
    <main class="main-principal">
        {% if name == 'HOME' %}
            {% block info %}{% endblock info %}
        {% elif name == 'BLOG' %}
            {% block posts %}{% endblock posts %}
        {% else %}
            <p>404</p>
        {% endif %}
    </main>
    {% include "./partials/footer.html" %}
</body>
</html>

templates/global/partials/footer.html
<footer class="rodape">
    <p>Site construído em Django - Copyright &copy; 2024</p>
</footer>

templates/global/partials/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" href="{% static "global/css/style.css" %}">
</head>

templates/global/partials/menu.html
<nav>
    <ul>
        <li><a href="{% url "home" %}">Home</a></li>
        <li><a href="{% url "blog:home" %}">Blog</a></li>
        <li><a href="#">Contact</a></li>
    </ul>
</nav>